// <auto-generated />
namespace MyWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SomePropertiesChangingv3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SomePropertiesChangingv3));
        
        string IMigrationMetadata.Id
        {
            get { return "201608191816564_SomePropertiesChangingv3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
